// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomCode: __t.string().primaryKey().name("room_code"),
  hostIdentity: __t.identity().name("host_identity"),
  topic: __t.string(),
  rounds: __t.u32(),
  roundTimeLimit: __t.u32().name("round_time_limit"),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
