// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const MuteState = __t.object("MuteState", {
  id: __t.u64(),
  muterIdentity: __t.identity(),
  mutedIdentity: __t.identity(),
  isMuted: __t.bool(),
});
export type MuteState = __Infer<typeof MuteState>;

export const PeerSignal = __t.object("PeerSignal", {
  id: __t.u64(),
  fromIdentity: __t.identity(),
  toIdentity: __t.identity(),
  roomCode: __t.string(),
  signalType: __t.string(),
  signalData: __t.string(),
  createdAt: __t.timestamp(),
});
export type PeerSignal = __Infer<typeof PeerSignal>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  roomCode: __t.string(),
  name: __t.string(),
  isHost: __t.bool(),
  isOnline: __t.bool(),
  currentScore: __t.u32(),
  joinedAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const Room = __t.object("Room", {
  roomCode: __t.string(),
  hostIdentity: __t.identity(),
  topic: __t.string(),
  rounds: __t.u32(),
  roundTimeLimit: __t.u32(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

