// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BulkSetMuteReducer from "../bulk_set_mute_reducer";
import CleanupSignalsReducer from "../cleanup_signals_reducer";
import CleanupSignalsForPeerReducer from "../cleanup_signals_for_peer_reducer";
import CreateRoomReducer from "../create_room_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import SendSignalReducer from "../send_signal_reducer";
import SetMuteReducer from "../set_mute_reducer";
import UpdateRoomStatusReducer from "../update_room_status_reducer";

export type BulkSetMuteParams = __Infer<typeof BulkSetMuteReducer>;
export type CleanupSignalsParams = __Infer<typeof CleanupSignalsReducer>;
export type CleanupSignalsForPeerParams = __Infer<typeof CleanupSignalsForPeerReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type SendSignalParams = __Infer<typeof SendSignalReducer>;
export type SetMuteParams = __Infer<typeof SetMuteReducer>;
export type UpdateRoomStatusParams = __Infer<typeof UpdateRoomStatusReducer>;

